name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or the version you are using

      - name: Update dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint '**/*.{js,jsx,ts,tsx}'

      - name: Run Prettier
        run: npx prettier --check '**/*.{js,jsx,ts,tsx,css,md}'

  format:
    runs-on: ubuntu-latest
    needs: lint-and-format

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or the version you are using

      - name: Update dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier to fix formatting issues
        run: npx prettier --write '**/*.{js,jsx,ts,tsx,css,md}'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Apply formatting changes'
          file_pattern: '**/*.{js,jsx,ts,tsx,css,md}'
